---
title: "About Requalverse"
categories:
  - requalverse
---

Requalverse is a conceptual framework for the development of Requal as an open source research software in accordance with FOSS principles. The framework gives users the freedom and tools to modify Requal to suit their analytical needs and preferences. Requal itself depends on the well-established culture of openness, collaboration, and sharing in the R community. With this background, Requalverse transcends the paradigms of closed-source, proprietary CAQDAS and implements the infrastructure of open-source software for computer-assisted qualitative data analysis.

Through building Requalverse, we not only aim to provide more capabilities and features to the users, but also to bridge the qualitative and quantitative research communities, support mixed-method research, and open new pathways for qualitative data analysis.

Requalverse takes the technical form of a collection of open source R packages that extend the functionality of Requal by following a simple set of development guidelines. Each package in the Requalverse is a miniature Shiny application that can be launched from the Requal app. It can be simple and oriented towards a specific task or as complex as its developers see fit. The architecture of the extension modules even allows them to be used as self-contained applications, although most of them will be probably tailored to work within the context of Requal.

On the Requal side, we provide an API interface that simplifies database operations and data transfer between the Requal app and Requalverse packages. Requal continues to handle user permissions and data integrity. At the same time, users retain full control over which extensions are installed and used in their projects.

